#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
# Make nginx listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
# Create a custom HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# Restart nginx service
sudo service nginx restart
