#!/usr/bin/env bash
#Install nginx web server and Redirection
custom_header="add_header X-Served-By \$hostname"

sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=xZIwIoekjgw;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\t$custom_header;/" /etc/nginx/sites-available/default
sudo service nginx restart
