#!/usr/bin/env bash
# Using HAProxy to load balance                         # between two web servers

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 347145-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 347145-web-02 54.145.241.45:80 check\n\tserver 347145-web-01 100.25.142.90:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start