#!/usr/bin/env bash
# Set the date format for the backup file
date=$(date +"%d-%m-%Y")

# Dump all databases into a sql file
mysqldump -u root -p"$1" --all-databases > backup.sql

# Compress the sql file into a tar.gz archive
tar -czvf "$date.tar.gz" backup.sql
