#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
if [ -e "school" ]; then
    echo "school exists"

    if [ -s "school" ]; then
        echo "school is not empty"
    else
        echo "school is empty"
    fi

    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
elsej
    echo "school does not exist"
fi